{% set version = '1.0.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggfocus
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggfocus_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggfocus/ggfocus_{{ version }}.tar.gz
  sha256: 6bbb8011938043fa5a828b60f4d1ea3e6263be2b954d9a21621a55eacecf000f

build:
  merge_build_host: True  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcolorbrewer
    - r-dplyr
    - r-ggplot2
    - r-magrittr
    - r-rlang
  run:
    - r-base
    - r-rcolorbrewer
    - r-dplyr
    - r-ggplot2
    - r-magrittr
    - r-rlang

test:
  commands:
    - $R -e "library('ggfocus')"           # [not win]
    - "\"%R%\" -e \"library('ggfocus')\""  # [win]

about:
  home: https://github.com/Freguglia/ggfocus
  license: GPL-3
  summary: A 'ggplot2' extension that provides tools for automatically creating scales to focus
    on subgroups of the data plotted without losing other information.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: ggfocus
# Type: Package
# Title: Scales that Focus Specific Levels in your ggplot()
# Version: 1.0.0
# Authors@R: person("Victor", "Freguglia", email = "victorfreguglia@gmail.com", role = c("aut", "cre"))
# BugReports: https://github.com/Freguglia/ggfocus/issues
# URL: https://github.com/Freguglia/ggfocus
# Description: A 'ggplot2' extension that provides tools for automatically creating scales to focus on subgroups of the data plotted without losing other information.
# License: GPL-3
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 7.0.2
# Depends: ggplot2
# Imports: magrittr, dplyr, rlang, RColorBrewer
# Suggests: knitr, rmarkdown, maps, ggrepel
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2020-01-22 19:00:47 UTC; victor
# Author: Victor Freguglia [aut, cre]
# Maintainer: Victor Freguglia <victorfreguglia@gmail.com>
# Repository: CRAN
# Date/Publication: 2020-01-23 13:20:02 UTC
