{% set version = '0.9' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggfocus
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggfocus_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggfocus/ggfocus_{{ version }}.tar.gz
  sha256: 7528ea31996c72b3774404d59ac9063cb336c1c9862b20189eec51d8eec04d0d

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-rcolorbrewer
    - r-dplyr
    - r-ggplot2
    - r-magrittr
    - r-rlang
  run:
    - r-base
    - r-rcolorbrewer
    - r-dplyr
    - r-ggplot2
    - r-magrittr
    - r-rlang

test:
  commands:
    - $R -e "library('ggfocus')"           # [not win]
    - "\"%R%\" -e \"library('ggfocus')\""  # [win]

about:
  home: https://github.com/Freguglia/ggfocus
  license: MIT
  summary: A 'ggplot2' extension that provides tools for automatically focusing specific factor
    levels.
  license_family: MIT

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: ggfocus
# Type: Package
# Title: Focus on Specific Factor Levels in your ggplot()
# Version: 0.9
# Author: Victor Freguglia
# Maintainer: Victor Freguglia <victorfreguglia@gmail.com>
# BugReports: https://github.com/Freguglia/ggfocus/issues
# URL: https://github.com/Freguglia/ggfocus
# Description: A 'ggplot2' extension that provides tools for automatically focusing specific factor levels.
# License: MIT + file LICENSE
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.1.1
# Depends: ggplot2
# Imports: magrittr, dplyr, rlang, RColorBrewer
# Suggests: knitr, rmarkdown, gapminder, ggmap
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2019-01-05 15:02:17 UTC; victor
# Repository: CRAN
# Date/Publication: 2019-01-07 18:40:06 UTC
