appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: s1yfoWTlVJ97mXHQaclcTUMKW9XZzEkIk/8P357+L7rmNAsnK4z7R54Ny5QEv931wyqslnEPwNHRuoYU0/Tg2VLc1LRRCXtzQvYdQYvm1Q/5GgSlS7OLBhw2AwHenNtX7KutXqBffzjZZuaq0/04nnv3gGCoX8Wl7Fp+cDUzdp99CuVMDu1/7gURmzudTIKanlemdeC/awVAHZ3hJ18gWlg0Ek2N5Eb5/Zf+6Dwk+MktamavHS3G41EzGtE46TrUxkuidWpAFlAhckbmb8pXw7c56fBNQ19LnZxT9I0xtL9Z2btCB5GY/TCQ56TlnzAPTaOspiU3C8aPaF7+sXat9rYuz4tybPjBZ2iwVoU/VksPqwPnIsvuFWUsOzLb1FlK+r1UtUnUMi+BuvjY4OqPYj0T+tm8HhbubIy3eYyEqgbzheFcKnsSGO8ZwypWM68sg3IRQ9Dx5O2BccGA1xuJfHhLyI4Jbfge+9v+eFEzQcXv/AzJNEjy2h2XfcRrp9PtLolITn0dqpps1yuYQ394jCI7VqhvCizS2fr1Wz89ihW77+o+dGntHY9nFqqPhcUDzGyIrTWqoRnsW5l4l4++/YLekfnV9QahS5gsMCCHoIjeJ7fHr5GBxEmNpsIWSIMEasQsLbMYnmkiFcytY9WxFVZsobXvu4fpsTD0siI2tS4=}
bot:
  automerge: true
